config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  get "/profile", to: "pages#profile", as: "profile"
  get "/terms_of_service", to: "pages#terms_of_service", as: "terms_of_service"
  get "/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"

  resources :projects

  resources :blog_posts

  resources :contacts, only: [:new, :create]
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  # Associations
  belongs_to :user # creates a method `blog_post.users` that shows who the owner / creator of the blog_post is.

  # Validations
  validates :title, presence: true
  validates :description, presence: true
  validates :img_url, presence: true
  validates :tags, presence: true
  validates :html_content, presence: true
  validates :user_id, presence: true
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
    @blog_posts = BlogPost.all
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    @blog_post.user = current_user

    if @blog_post.save
      redirect_to blog_post_path(@blog_post), notice: "Blog post was successfully created!"
    else
      render "new", alert: "Blog post failed to create. Please try again!", status: :unprocessable_entity
    end
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def update
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.update(blog_post_params)
      redirect_to blog_post_path(@blog_post), notice: "Blog post was successfully edited!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.destroy
      redirect_to blog_posts_path, notice: "Blog post was successfully deleted!", status: :see_other
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :description, :img_url, :tags, :html_content, :user_id)
  end
end

app/views/blog_posts/_blog_post_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.7)), url(<%= asset_path(blog_post.img_url) %>);">
  <div class="container">
    <h1 class="mt-5 mb-4 fs-1"><%= blog_post.title %></h1>
  </div>
</div>

app/views/blog_posts/_blog_post_hero_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.7)), url(<%= asset_path(blog_post.img_url) %>);">
  <div class="container">
    <header>
      <h1 class="mt-5 mb-2 fs-1"><%= blog_post.title %></h1>
      <p class="text-light small">Posted on <%= blog_post.created_at.strftime("%B %d, %Y") %></p>
      <!-- Share button -->
      <div data-controller="clipboard">
        <%= link_to "#", data: { action: "click->clipboard#copy", clipboard_target: "shareButton" }, class: "btn btn-outline-light rounded-4 p-2 my-2" do %>
          <i class="fa-solid fa-arrow-up-from-bracket"></i> Share
        <% end %>
        <input type="hidden" value="<%= blog_post_url(@blog_post) %>" data-clipboard-target="source">
      </div>
      <!-- Edit buttons for signed in user -->
      <% if user_signed_in? %>
        <div class="d-flex justify-content-between align-items-center">
          <%= link_to "Back to Blog", blog_posts_path, class: "btn btn-secondary rounded-4 p-2 mt-3" %>
          <div class="d-flex gap-4 justify-content-start align-items-center">
            <%= link_to "Edit Post", edit_blog_post_path, class: "btn btn-primary rounded-4 p-2 mt-3" %>
            <%= link_to blog_post_path(@blog_post), data: { turbo_method: :delete, turbo_confirm: "Delete blog post ?" } do %>
              <i class="fa-regular fa-trash-can text-danger trash-grow fs-2 mt-3"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </header>
  </div>
</div>

app/views/blog_posts/_blog_posts_hero_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.7)), url(<%= asset_path('abstract-coral-2.jpg') %>);">
  <div class="container">
    <header>
      <h1 class="mt-5 mb-4 fs-1"><i class="fa-solid fa-feather"></i> Blog</h1>
      <p>Explore practical tutorials and coding insights from my blog.</p>
      <% if user_signed_in? %>
        <%= link_to "Create", new_blog_post_path, class: "btn btn-primary rounded-4 p-2 mt-1" %>
      <% end %>
    </header>
  </div>
</div>

app/views/blog_posts/_edit_hero_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.7)), url(<%= asset_path(blog_post.img_url) %>);">
  <div class="container">
    <header>
      <h1 class="mt-5 mb-4 fs-1"><i class="fa-solid fa-pen-to-square text-info"></i> <%= blog_post.title %></h1>
    </header>
  </div>
</div>

app/views/blog_posts/_new_hero_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.7)), url(<%= asset_path('abstract-1.jpg') %>);">
  <div class="container">
    <header>
      <h1 class="mt-5 mb-4 fs-1"><i class="fa-solid fa-rocket text-success"></i> Create Blog Post</h1>
    </header>
  </div>
</div>

app/views/blog_posts/edit.html.erb
<!-- Blog post edit -->
<%= render "edit_hero_banner", blog_post: @blog_post %>
<div class="container">
  <main>
    <section id="edit-blog-post">
      <h2 class="mt-5 mb-4">Edit blog post</h2>
      <%= simple_form_for @blog_post do |f| %>
        <%= f.input :title, label: "Blog Post Title", hint: "Make the title 3-4 words long for optimal blog post card height. Capitalize the beginning of each word." %>
        <%= f.input :description, as: :text, label: "Blog Post Description", hint: "Make the description 30-40 words long to optimally fill out the blog post cards." %>
        <%= f.input :img_url, label: "Featured Image URL", hint: "Use image aspect ratio 3:2 (w:h). Preference is to use images already in the project folder (file extensions must be included eg. .svg, .jpg, .png). Careful! Typos will break the app. Can also use an external URL starting with HTTPS://", placeholder: "abstract-waves" %>
        <%= f.input :tags, label: "Tags", placeholder: "Rails 7 . ActionMailer . Gmail . Heroku . Contact Form . Tutorial", hint: "Add tags to categorize the blog post and identify the post type eg. tutorial, code or career insights? Order doesn't matter. Show 2-6 tags (capitalized) and separating each one with ' . '" %>
        <%= f.input :html_content, as: :text, rows: 12, label: "HTML Code For Your Blog Post", hint: "Guide: (1) Use single quotes ' ' for HTML attribute values and escape any apostrophes inside with a 'backslash' in front, (2) can use bootstrap and custom classes as well as inline styles, (3) the <style> element doesn't work and is meant to be in the <head>, (4) the attribute target='_blank' attribute doesn't work and may be sanitized, (5) adding plain text without any HTML won't break the web app, (6) your HTML code is already wrapped inside the following elements: <div class='container'><article>[YOUR CODE]</article></div>, (7) keep to a consistent style & familiar structure, (8) start the blog post with a <h2> tag (<h1> is already used once at the top of the page), (9) no <script> elements, and (10) optimize it for SEO.", placeholder: "<h1 class='text-primary'>Ruby on Rails History</h1> <p style='color: black; font-size: 16px text-align: left;'>Before <a href='https://rubyonrails.org/' target='_blank' title='Can\'t open this'>Rails</a>, web development was often tedious, requiring developers to write boilerplate code for repetitive tasks like database queries, request handling, and routing. Rails introduced a revolutionary principle: Convention over Configuration.</p>" %>
        <div class="d-flex justify-content-end my-4 gap-3">
          <%= f.button :submit, "Submit", class: "btn btn-primary rounded-4 p-2" %>
          <%= link_to "Cancel", blog_posts_path, class: "btn btn-outline-dark rounded-4 p-2" %>
        </div>
      <% end %>
    </section>
  </main>
</div>

app/views/blog_posts/index.html.erb
<!-- Blog posts index -->
<%= render "blog_posts_hero_banner" %>
<div class="container">
  <main>
    <section id="blog-posts-index">
      <div class="row justify-content-start align-items-center">
        <h2 class="mt-5 mb-4">Blog Posts</h2>
        <% @blog_posts.each do |blog_post| %>
          <div class="col-12 col-md-6 col-lg-4">
            <div class="card card-blog-post shadow-sm rounded-4 mb-4">
              <div class="card-body p-4">
                 <%= link_to blog_post_path(blog_post), class: "text-decoration-none text-dark" do %>
                  <h3 class="card-title fw-bold mb-4"><%= blog_post.title %></h3>
                <% end %>
                <%= image_tag blog_post.img_url, alt: "Blog post featured image", class: "img-fluid rounded-4 mb-3 border border-secondary" %>

                <p class="card-text small text-muted">Posted on <%= blog_post.created_at.strftime("%B %d, %Y") %></p>
                <p class="card-text text-muted"><%= blog_post.description.capitalize %></p>
                <hr class="my-3">
                <p class="text-blog-tags">
                  <%= blog_post.tags %>
                </p>
                <div class="d-flex justify-content-center align-items-center">
                  <%= link_to "View Full Post", blog_post_path(blog_post), class: "btn btn-outline-dark outline-d-btn rounded-4 px-4 py-2 fw-medium w-100 my-3" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </section>
  </main>
</div>

app/views/blog_posts/new.html.erb
<!-- Blog post new -->
<%= render "new_hero_banner" %>
<div class="container">
  <main>
    <section id="new-blog-post">
      <h2 class="mt-5 mb-4">New blog post</h2>
      <%= simple_form_for @blog_post do |f| %>
        <%= f.input :title, label: "Blog Post Title", hint: "Make the title 3-4 words long for optimal blog post card height. Capitalize the beginning of each word." %>
        <%= f.input :description, as: :text, label: "Blog Post Description", hint: "Make the description 30-40 words long to optimally fill out the blog post cards." %>
        <%= f.input :img_url, label: "Featured Image URL", hint: "Use image aspect ratio 3:2 (w:h). Preference is to use images already in the project folder (file extensions must be included eg. .svg, .jpg, .png). Careful! Typos will break the app. Can also use an external URL starting with HTTPS://", placeholder: "abstract-waves" %>
        <%= f.input :tags, label: "Tags", placeholder: "Rails 7 . ActionMailer . Gmail . Heroku . Contact Form . Tutorial", hint: "Add tags to categorize the blog post and identify the post type eg. tutorial, code or career insights? Order doesn't matter. Show 2-6 tags (capitalized) and separating each one with ' . '" %>
        <%= f.input :html_content, as: :text, rows: 12, label: "HTML Code For Your Blog Post", hint: "Guide: (1) Use single quotes ' ' for HTML attribute values and escape any apostrophes inside with a 'backslash' in front, (2) can use bootstrap and custom classes as well as inline styles, (3) the <style> element doesn't work and is meant to be in the <head>, (4) the attribute target='_blank' attribute doesn't work and may be sanitized, (5) adding plain text without any HTML won't break the web app, (6) your HTML code is already wrapped inside the following elements: <div class='container'><article>[YOUR CODE]</article></div>, (7) keep to a consistent style & familiar structure, (8) start the blog post with a <h2> tag (<h1> is already used once at the top of the page), (9) no <script> elements, and (10) optimize it for SEO.", placeholder: "<h1 class='text-primary'>Ruby on Rails History</h1> <p style='color: black; font-size: 16px text-align: left;'>Before <a href='https://rubyonrails.org/' target='_blank' title='Can\'t open this'>Rails</a>, web development was often tedious, requiring developers to write boilerplate code for repetitive tasks like database queries, request handling, and routing. Rails introduced a revolutionary principle: Convention over Configuration.</p>" %>
        <div class="d-flex justify-content-end my-4 gap-3">
          <%= f.button :submit, "Create", class: "btn btn-primary rounded-4 p-2" %>
          <%= link_to "Cancel", blog_posts_path, class: "btn btn-outline-dark rounded-4 p-2" %>
        </div>
      <% end %>
    </section>
  </main>
</div>

app/views/blog_posts/new_hero_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.7)), url(<%= asset_path('abstract-waves') %>);">
  <div class="container">
    <h1 class="mt-5 mb-4 fs-1">Create Project <i class="fa-solid fa-rocket text-success"></i></h1>
  </div>
</div>

app/views/blog_posts/show.html.erb
<!-- Blog post show -->
<%= render "blog_post_hero_banner", blog_post: @blog_post %>
<div class="container">
  <main>
    <article data-controller="html-inject" class="mt-5 mb-4" hidden>
      <!-- textContent (HTML string) that's inside <article> element -->
      <!-- Rails `sanitize` helper method cleans + marks safe → Rails ERB automatically converts any sanitized (or html_safe marked) HTML string to DOM → Stimulus just un-hides on connect(). This renders sanitized HTML directly on page load via Stimulus connect() -->
      <%= sanitize @blog_post.html_content %>
    </article>
  </main>
</div>