config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  get "/profile", to: "pages#profile", as: "profile"
  get "/terms_of_service", to: "pages#terms_of_service", as: "terms_of_service"
  get "/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"

  resources :projects

  resources :blog_posts

  resources :contacts, only: [:new, :create]
end

app/views/shared/_flashes.html.erb
<%= flash[:error] %>
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container-fluid bg-dark p-4 mt-5">
  <footer>
    <div class="row g-4">
      <!-- Left: Nav Links -->
      <div class="col-12 col-md-4">
        <div class="d-flex flex-column flex-md-row justify-content-center justify-content-md-start align-items-center gap-3 gap-md-4">
          <% if !user_signed_in? && current_page?("/projects") %>
            <%= link_to "Login", new_user_session_path, class: "gray-link text-decoration-none" %>
          <% end %>
          <%= link_to "Terms of Use", terms_of_service_path, class: "gray-link text-decoration-none" %>
          <%= link_to "Privacy Policy", privacy_policy_path, class: "gray-link text-decoration-none" %>
        </div>
      </div>
      <!-- Center: Copyright -->
      <div class="col-12 col-md-4 text-center">
        <div class="gray-non-link">
          © 2025 Louis Bourne. All rights reserved.
        </div>
      </div>
      <!-- Right: Social Icons -->
      <div class="col-12 col-md-4">
        <div class="social-horizontal d-flex justify-content-center justify-content-md-end align-items-center gap-4">
          <%= link_to "https://www.fiverr.com/s/LdGw534", target: "_blank", rel: "noopener" do %>
            <i class="fa-solid fa-briefcase fs-5"></i>
          <% end %>
          <%= link_to "https://github.com/louiskb", target: "_blank", rel: "noopener" do %>
            <i class="fa-brands fa-github fs-5"></i>
          <% end %>
          <%= link_to "https://www.linkedin.com/in/louis-bourne/", target: "_blank", rel: "noopener" do %>
            <i class="fa-brands fa-linkedin fs-5"></i>
          <% end %>
          <%= link_to "https://discord.com/users/brothercap", target: "_blank", rel: "noopener" do %>
            <i class="fa-brands fa-discord fs-5"></i>
          <% end %>
          <%= link_to "mailto:dev@louisbourne.me", target: "_blank", rel: "noopener" do %>
            <i class="fa-solid fa-envelope fs-5"></i>
          <% end %>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark navbar-lb" style="background-color: rgba(0, 0, 0, 0.90);">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand ms-2" do %>
      <%= image_tag "lb-circle-logo-light-tp.png", alt: "Logo" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Portfolio", root_path, class: nav_link_class(root_path) %>
          </li>
          <li class="nav-item">
            <%= link_to "Projects", projects_path, class: nav_link_class(projects_path) %>
          </li>
          <li class="nav-item me-1">
            <%= link_to "Blog", blog_posts_path, class: nav_link_class(blog_posts_path) %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle ms-2" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "dog-pixar.jpg", class: "avatar", alt: "Dropdown menu and user avatar image." %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create Project", new_project_path, class: nav_link_dropdown_class(new_project_path) %>
              <%= link_to "Create Blog Post", new_blog_post_path, class: nav_link_dropdown_class(new_blog_post_path) %>
              <%= link_to "Profile", profile_path, class: nav_link_dropdown_class(profile_path) %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-dark fs-5" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <!-- Desktop -->
            <%= link_to "Portfolio", root_path, class: nav_link_class(root_path) %>
          </li>
          <li class="nav-item">
            <%= link_to "Projects", projects_path, class: nav_link_class(projects_path) %>
          </li>
          <li class="nav-item me-2">
            <%= link_to "Blog", blog_posts_path, class: nav_link_class(blog_posts_path) %>
          </li>
          <li class="nav-item me-2 my-1">
            <%= link_to "Contact Me", root_path(anchor: "contact"), class: "btn btn-primary fs-5 btn-lg rounded-5 btn-nav" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>