config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  get "/profile", to: "pages#profile", as: "profile"
  get "/terms_of_service", to: "pages#terms_of_service", as: "terms_of_service"
  get "/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"

  resources :projects

  resources :blog_posts

  resources :contacts, only: [:new, :create]
end

app/views/pages/_about_me.html.erb
<!-- About me -->
<section id="about-me" class="bg-waves-2 container-fluid p-5 my-5">
  <div class="container">
    <h2 class="h2-d mb-4">About me</h2>
    <div class="row justify-content-center">
      <div class="col-12 col-md-6">
        <%= image_tag "rails-dev-1.jpg", alt: "Louis web developer", class: "w-100 border border-light border-5 rounded-4 shadow mb-4" %>
      </div>
      <div class="col-12 col-md-6">
        <p class="text-about fs-5">Mixed British-Thai developer based in Thailand, which I now call home after growing up across multiple countries. Fluent in English and Thai, with a long-standing love of tech 🤓 that naturally led into full‑stack development. Also an independent trader and financial analyst, combining technical charting with a structured, risk‑first approach to the markets 📊.
        </p>
      </div>
    </div>
    <!-- Adventure -->
    <div class="row my-3">
      <div class="col-12 col-md-6">
        <%= image_tag "mt-cook-ta.jpg", alt: "Louis web developer", class: "w-100 border border-light border-5 rounded-4 shadow mb-4" %>
      </div>
      <div class="col-12 col-md-6">
        <p class="text-about fs-5">Beyond code and charts, staying active is a big part of life - lifting, kitesurfing, running, and hiking - and that love of adventure took me all the way through New Zealand’s 3,000 km Te Araroa thru‑hike, which I completed over four months in 2024/2025 🚀.</p>
      </div>
    </div>
    <!-- Thai PBS 2C -->
    <div class="row my-3">
      <div class="col-12 col-md-6">
        <div class="border border-light border-5 rounded-4 shadow">
          <!-- width="560" -->
          <iframe height="350" src="https://www.youtube.com/embed/X427QTamroE?si=cIjvoF9l_rCW2GHn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" class="w-100" allowfullscreen></iframe>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <h4 class="h1-d mt-4 mb-3">Thai PBS - 2C Climate Change Documentary Series (2019): Episode 4</h4>
        <p class="text-about fs-5 mb-4">Served as a TV presenter for a five‑episode climate change documentary along the Gulf of Thailand, covering the coastlines of Thailand, Cambodia, and Vietnam. The series explores key environmental challenges across Southeast Asia and still airs on Thai national TV.</p>
      </div>
    </div>
  </div>
</section>

app/views/pages/_contact.html.erb
<!-- Contact -->
<section id="contact">
  <div class="container">
    <div class="card shadow-sm rounded-4 my-3">
      <div class="card-body p-4">
        <h2 class="mb-3">Contact me</h2>
        <p class="card-text mb-5">Want to collaborate or discuss a project? <br>
          <br>
          Fill out the form below or email me directly at
          <%= link_to "dev@louisbourne.me", "mailto:dev@louisbourne.me", target: "_blank", class: "text-decoration-none" %>. <br>
          <br>
          Currently open to full‑time roles and new opportunities, and also taking on <%= link_to "Fiverr", "https://www.fiverr.com/s/LdGw534", target: "_blank", class: "text-decoration-none" %> projects to build Ruby on Rails apps, MVPs, and custom products.
        </p>
        <!-- Contact form -->
       <%= simple_form_for @contact, url: contacts_path, local: true, data: { controller: "load-button" }, class: "mb-2" do |f| %>
        <div class="row">
          <div class="col-12 col-md-6">
            <%= f.input :first_name, label: "First Name" %>
          </div>
          <div class="col-12 col-md-6">
            <%= f.input :last_name, label: "Last Name" %>
          </div>
        </div>
        <%= f.input :email, label: "Your Email" %>
        <%= f.input :message, as: :text, rows: 6, label: "Message" %>
        <!-- Hp -->
        <%= invisible_captcha %>
        <!-- Submit button -->
        <%= f.button :submit, "Send Message", data: { action: "click->load-button#loader" }, class: "btn btn-primary btn-lg rounded-5 mb-4 mt-4" %>
       <% end %>
      </div>
    </div>
  </div>
</section>

app/views/pages/_demo_day.html.erb
<!-- Demo day -->
<section id="demo-day" class="bg-waves-1 container-fluid p-5 my-5">
  <div class="container">
    <div class="row my-5">
      <div class="col-12 col-md-6">
        <h2 class="h1-d mb-3">Le Wagon Tokyo demo day</h2>
        <h4 class="h4-d mb-5">Showcasing our demo app <%= link_to "Market Sensei", "https://www.marketsensei.app/", target: "_blank", class: "text-decoration-none" %> at Le Wagon Tokyo demo day, hosted by Google for Startups.</h4>
      </div>
      <div class="col-12 col-md-6">
        <div class="border border-light border-5 rounded-4 shadow">
          <!-- width="560" -->
          <iframe height="350" src="https://www.youtube.com/embed/4xmj3REIGe0?si=YLU2WypZ70-SUjgb&amp;start=5030" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" class="w-100" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_education.html.erb
<!-- Education -->
<section id="education">
  <div class="container">
    <h3 class="mb-3">Education & certifications</h3>
    <p>My education background and key certifications sorted by most recent first.</p>
    <div class="row justify-content-center">
      <!-- Le Wagon certification -->
      <div class="col-12 col-lg-6">
        <div class="card card-education shadow-sm rounded-4 my-3">
          <div class="card-body p-4">
            <div class="d-flex justify-content-start align-items-top gap-4">
              <%= image_tag "tokyo-learn-card.jpg", alt: "Learn digital marketing online", class: "img-fluid w-25 rounded-3" %>
              <div>
                <%= link_to "https://www.lewagon.com/", class: "text-decoration-none fs-5", target: "_blank" do %>
                  Le Wagon <i class="fa-solid fa-code"></i>
                <% end %>
                <p class="card-text text-muted small">AI Software Development Bootcamp <br>
                  <span class="small">Tokyo, Japan 🇯🇵 · 2025</span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Nucamp certification -->
      <div class="col-12 col-lg-6">
        <div class="card card-education shadow-sm rounded-4 my-3">
          <div class="card-body p-4">
            <div class="d-flex justify-content-start align-items-top gap-4">
              <%= image_tag "nucamp-learn-card.jpg", alt: "Learn digital marketing online", class: "img-fluid w-25 rounded-3" %>
              <div>
                <%= link_to "https://www.nucamp.co/", class: "text-decoration-none fs-5", target: "_blank" do %>
                  Nucamp <i class="fa-solid fa-code"></i>
                <% end %>
                <p class="card-text text-muted small">Full Stack Web and Mobile Development Bootcamp <br>
                  <span class="small">Online 👨‍💻 · 2023-2024</span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- LearnToTrade UK -->
      <div class="col-12 col-lg-6">
        <div class="card card-education shadow-sm rounded-4 my-3">
          <div class="card-body p-4">
            <div class="d-flex justify-content-start align-items-top gap-4">
              <%= image_tag "learntotrade.jpg", alt: "Learn to trade online", class: "img-fluid w-25 rounded-3" %>
              <div>
                <%= link_to "https://learntotradegroup.com/", class: "text-decoration-none fs-5", target: "_blank" do %>
                  LearnToTrade, UK <i class="fa-solid fa-chart-simple"></i>
                <% end %>
                <p class="card-text text-muted small">Unlimited Wealth Program <br>
                  <span class="small">Online 👨‍💻 · 2020-2021</span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Digital Marketing Institute certification -->
      <div class="col-12 col-lg-6">
        <div class="card card-education shadow-sm rounded-4 my-3">
          <div class="card-body p-4">
            <div class="d-flex justify-content-start align-items-top gap-4">
              <%= image_tag "dmi-learn-card.jpg", alt: "Learn digital marketing online", class: "img-fluid w-25 rounded-3" %>
              <div>
                <%= link_to "https://digitalmarketinginstitute.com/", class: "text-decoration-none fs-5", target: "_blank" do %>
                  Digital Marketing Institute <i class="fa-solid fa-bullhorn"></i>
                <% end %>
                <p class="card-text text-muted small">Professional Diploma in Digital Marketing <br>
                  <span class="small">Online 👨‍💻 · 2018</span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Newcastle University certification -->
      <div class="col-12 col-lg-6">
        <div class="card card-education shadow-sm rounded-4 my-3">
          <div class="card-body p-4">
            <div class="d-flex justify-content-start align-items-top gap-4">
              <%= image_tag "ncl-learn-card.jpg", alt: "Learn digital marketing online", class: "img-fluid w-25 rounded-3" %>
              <div>
                <%= link_to "https://www.ncl.ac.uk/", class: "text-decoration-none fs-5", target: "_blank" do %>
                  Newcastle University <i class="fa-solid fa-graduation-cap"></i>
                <% end %>
                <p class="card-text text-muted small">Bachelor of Science in Marine Biology <br>
                  <span class="small">Newcastle Upon-Tyne, UK 🇬🇧 · 2008-2011</span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Download full resume button -->
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "/docs/louis-bourne-full-stack-developer-resume-jan-2026.pdf", download: "louis-bourne-full-stack-developer-resume-dec-2025.pdf", class: "btn btn-outline-dark btn-lg rounded-5 mb-3 mt-5" do %>
        <i class="fa-solid fa-download"></i> Download Full Resume
      <% end %>
    </div>
  </section>

app/views/pages/_featured_projects.html.erb
<!-- Featured projects -->
<section id="featured-projects">
  <div class="container">
    <div class="row justify-content-start align-items-center">
      <!-- Personal projects -->
      <h2 class="mt-5 mb-4">Featured projects</h2>
      <% @personal_projects.each do |project| %>
        <div class="col-12 col-md-6 col-lg-4">
          <div class="card card-project shadow-sm rounded-4 mb-4">
            <div class="card-body p-4">
              <h3 class="card-title fw-bold mb-2"><%= project.title.capitalize %></h3>
              <p class="card-text small text-muted mb-3">
                <%= project.description %>
              </p>
              <%= image_tag project.img_url, alt: "Project screenshot", class: "img-fluid rounded-4 mb-3 border border-secondary" %>
              <!-- <p class="mb-4 text-secondary text-tech-stack">
              Ruby-on-Rails &nbsp;.&nbsp; JavaScript &nbsp;.&nbsp; Ruby &nbsp;.&nbsp; PostgreSQL
            </p> -->
              <p class="mb-4 text-secondary text-tech-stack">
                <%= project.tech_stack %>
              </p>
              <div class="d-flex justify-content-between align-items-center mt-2">
                <% if project.private_repo %>
                  <% if user_signed_in? %>
                    <div class="d-flex justify-content-start align-items-start gap-2">
                      <%= link_to project.github_url, class: "btn btn-link github-btn p-0", target: "_blank", rel: "noopener" do %>
                        <i class="fa-brands fa-github fs-3 text-dark"></i>
                      <% end %>
                      <p class="small text-dark">private</p>
                    </div>
                  <% else %>
                    <div class="d-flex justify-content-start align-items-start gap-2">
                      <i class="fa-brands fa-github fs-3 light-gray"></i>
                      <p class="small light-gray">private</p>
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to project.github_url, class: "btn btn-link github-btn p-0", target: "_blank", rel: "noopener" do %>
                    <i class="fa-brands fa-github fs-3 text-dark"></i>
                  <% end %>
                <% end %>
                <%= link_to project.project_url, class: "btn btn-outline-dark outline-d-btn rounded-4 px-4 py-2 fw-medium", target: "_blank", rel: "noopener" do %>
                  <i class="fa-solid fa-arrow-up-right-from-square"></i> Live Demo
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div>
      <%= link_to "See more projects...", projects_path, class: "text-decoration-none fs-5" %>
    </div>
    <hr class="my-5">
    <!-- Open source project contributions-->
    <div class="row justify-content-center align-items-top">
      <% @open_source_projects.each do |project| %>
        <div class="col-12 col-md-6">
          <h2 class="text-start mb-3">Open source contributions</h2>
          <h4 class="text-start mb-5">Led the integration and continued development of <%= link_to "Storybook", "https://storybook.js.org/", class: "text-decoration-none", target: "_blank", rel: "noopener" %> for Find a Doc Japan (an open-source project), conducting snapshot testing with <span class="fst-italic">Jest</span> and <span class="fst-italic">Vitest</span> while collaborating with developers worldwide.</h4>
        </div>
        <div class="col-12 col-md-6">
          <div class="card card-project shadow-sm rounded-4 mb-4">
            <div class="card-body p-4">
              <h3 class="card-title fw-bold mb-2"><%= project.title.capitalize %></h3>
              <p class="card-text small text-muted mb-3">
                <%= project.description %>
              </p>
              <%= image_tag project.img_url, alt: "Open source project screenshot", class: "img-fluid rounded-4 mb-3 border border-secondary" %>
              <!-- <p class="mb-4 text-secondary text-tech-stack">
              Ruby-on-Rails &nbsp;.&nbsp; JavaScript &nbsp;.&nbsp; Ruby &nbsp;.&nbsp; PostgreSQL
            </p> -->
              <p class="mb-4 text-secondary text-tech-stack">
                <%= project.tech_stack %>
              </p>
              <div class="d-flex justify-content-between align-items-center mt-2">
                <% if project.private_repo %>
                  <% if user_signed_in? %>
                    <div class="d-flex justify-content-start align-items-start gap-2">
                      <%= link_to project.github_url, class: "btn btn-link github-btn p-0", target: "_blank", rel: "noopener" do %>
                        <i class="fa-brands fa-github fs-3 text-dark"></i>
                      <% end %>
                      <p class="small text-dark">private</p>
                    </div>
                  <% else %>
                    <div class="d-flex justify-content-start align-items-start gap-2">
                      <i class="fa-brands fa-github fs-3 light-gray"></i>
                      <p class="small light-gray">private</p>
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to project.github_url, class: "btn btn-link github-btn p-0", target: "_blank", rel: "noopener" do %>
                    <i class="fa-brands fa-github fs-3 text-dark"></i>
                  <% end %>
                <% end %>
                <%= link_to project.project_url, class: "btn btn-outline-dark outline-d-btn rounded-4 px-4 py-2 fw-medium", target: "_blank", rel: "noopener" do %>
                  <i class="fa-solid fa-arrow-up-right-from-square"></i> View Project
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/pages/_hero_banner.html.erb
<!-- Hero banner -->
<section id="hero-banner" class="d-flex justify-content-center align-items-start text-center">
  <%= render "social_vertical_bar" %>
  <div class="container mt-5">
    <div class="mt-5">
      <h1 class="text-light">
        Hi,<br>
        I'm Louis,<br>
        web developer
      </h1>
      <h2 class="gray">Fullstack Developer / Ruby-on-Rails</h2>
      <div class="mt-4">
        <%= link_to "Contact Me", "#", class: "btn btn-primary btn-lg custom-btn rounded-5" %>
        <!-- Once there are more than 6 projects add `Project` page to NavBar and change hero banner secondary button to "Key Projects". -->
        <!-- <%#= link_to "Key Projects", "#featured-projects", class: "btn btn-outline-light btn-lg rounded-5 custom-btn" %> -->
        <%= link_to "My Projects", "#featured-projects", class: "btn btn-outline-light btn-lg rounded-5 custom-btn" %>
      </div>
    </div>
    <div class="chevron-scroll">
      <%= link_to "#featured-projects", class: "d-flex flex-column align-items-center justify-content-center text-decoration-none" do %>
        <i class="fas fa-angle-double-down"></i>
      <% end %>
    </div>
  </div>
</section>

app/views/pages/_landing_hero_banner.html.erb
<!-- Hero banner -->
<div id="hero-banner" class="d-flex justify-content-center align-items-start text-center">
  <%= render "social_vertical_bar" %>
  <div class="container mt-5">
    <div class="mt-5">
      <h1 class="text-light">
        Hi,<br>
        I'm Louis,<br>
        web developer
      </h1>
      <h2 class="lighter-gray mb-4">Full-Stack Developer / Ruby-on-Rails</h2>
      <div class="d-flex justify-content-center align-items-center gap-3">
        <!-- CTA Button -->
        <!-- Desktop: large button (hidden on mobile) -->
        <%= link_to "Contact Me", "#contact", class: "btn btn-primary btn-lg fs-4 rounded-5 custom-btn d-none d-sm-block" %>
        <!-- Mobile: Small button (hidden on desktop) -->
        <%= link_to "Contact Me", "#contact", class: "btn btn-primary btn-sm rounded-5 custom-btn px-4 py-2 d-block d-sm-none"  %>
        <!-- Secondary Button -->
        <!-- Desktop: large button (hidden on mobile) -->
        <%= link_to "Key Projects", "#featured-projects", class: "btn btn-outline-light btn-lg fs-4 rounded-5 custom-btn d-none d-sm-block" %>
        <!-- Mobile: Small button (hidden on desktop) -->
        <%= link_to "Key Projects", "#featured-projects", class: "btn btn-outline-light btn-sm rounded-5 custom-btn px-4 py-2 d-block d-sm-none" %>
      </div>
    </div>
    <div class="chevron-scroll">
      <%= link_to "#featured-projects", class: "d-flex flex-column align-items-center justify-content-center text-decoration-none" do %>
        <i class="fas fa-angle-double-down"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_profile_hero_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.7)), url(<%= asset_path('abstract-kelp-2.jpg') %>);">
  <div class="container">
    <h1 class="mt-5 mb-4 fs-1"><i class="fa-solid fa-mug-hot text-light"></i> Welcome back Louis!</h1>
    <p>"What is one tiny action today that your future self will be genuinely grateful you did?"</p>
  </div>
</div>

app/views/pages/_social_vertical_bar.html.erb
<!-- Social vertical bar -->
<div class="social-vertical d-flex flex-column justify-content-center align-items-center">
  <%= link_to "https://www.fiverr.com/s/LdGw534", target: "_blank", rel:"noopener", class: "mb-3" do %>
    <i class="fa-solid fa-briefcase"></i>
  <% end %>
  <%= link_to "https://github.com/louiskb", target: "_blank", rel:"noopener", class: "mb-3" do %>
    <i class="fa-brands fa-github"></i>
  <% end %>
  <%= link_to "https://www.linkedin.com/in/louis-bourne/", target: "_blank", rel:"noopener", class: "mb-3" do %>
    <i class="fa-brands fa-linkedin"></i>
  <% end %>
  <%= link_to "https://discord.com/users/brothercap", target: "_blank", rel:"noopener", class: "mb-3" do %>
    <i class="fa-brands fa-discord"></i>
  <% end %>
  <%= link_to "mailto:dev@louisbourne.me", target: "_blank", rel:"noopener", class: "mb-3" do %>
    <!-- <i class="fa-regular fa-envelope"></i> -->
    <i class="fa-solid fa-envelope"></i>
  <% end %>
</div>

app/views/pages/_tech_stack.html.erb
 <!-- Tech stack -->
<section id="tech-stack">
  <div class="container">
    <h2 class="mb-3">Technology and skills</h2>
    <h4 class="fs-5 mb-2">What I know</h4>
    <div class="row">
      <div class="col-12 col-md-4">
        <h5 class="fs-6">Frontend</h5>
        <div class="d-flex justify-content-start align-items-center">
          <%= link_to "https://developer.mozilla.org/en-US/docs/Web/JavaScript", target: "_blank", rel: "noopener" do %>
            <%= image_tag "javascript.svg", alt: "JavaScript icon", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://developer.mozilla.org/en-US/docs/Web/HTML", target: "_blank", rel: "noopener" do %>
            <%= image_tag "html5.svg", alt: "HTML 5 icon", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://developer.mozilla.org/en-US/docs/Web/CSS", target: "_blank", rel: "noopener" do %>
            <%= image_tag "css3.svg", alt: "CSS 3 icon", class: "tech-icon p-3" %>
          <% end %>
        </div>
        <div class="d-flex justify-content-start align-items-center">
          <%= link_to "https://sass-lang.com/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "sass.svg", alt: "Sass icon", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://getbootstrap.com/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "bootstrap.svg", alt: "Bootstrap icon", class: "tech-icon p-3" %>
          <% end %>
        </div>
      </div>
      <div class="col-12 col-md-8">
        <h5 class="fs-6">Backend</h5>
        <div class="d-flex justify-content-start align-items-center">
          <%= link_to "https://www.ruby-lang.org/en/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "ruby.svg", alt: "Ruby icon", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://www.postgresql.org/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "postgresql.svg", alt: "PostgreSQL icon", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://rspec.info/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "rspec.svg", alt: "Rspec icon", class: "tech-icon p-3" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-4">
        <h5 class="fs-6 mt-3">Frameworks & libraries</h5>
        <div class="d-flex justify-content-start align-items-center">
          <%= link_to "https://rubyonrails.org/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "ruby-on-rails.svg", alt: "Ruby-on-rails icon", class: "tech-icon p-3" %>
          <% end %>
        </div>
      </div>
      <div class="col-12 col-md-8">
        <h5 class="fs-6 mt-3">Tools</h5>
        <div class="d-flex justify-content-start align-items-center">
          <%= link_to "https://www.github.com/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "github.svg", alt: "Github icon", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://www.figma.com/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "figma.svg", alt: "Figma icon", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://openai.com/api/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "ai-dark.svg", alt: "Third-party AI icon linking to OpenAI", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://storybook.js.org/", target: "_blank", rel: "noopener" do %>
            <%= image_tag "storybook.svg", alt: "Storybook.js logo", class: "tech-icon p-3" %>
          <% end %>
        </div>
      </div>
    </div>
    <h4 class="fs-5 mt-3 mb-2">What I'm learning</h4>
    <div class="row">
      <div class="col-12 col-md-6">
        <h5 class="fs-6">Frameworks & libraries</h5>
        <div class="d-flex justify-content-start align-items-center">
          <%= link_to "https://react.dev", target: "_blank", rel: "noopener" do %>
            <%= image_tag "react.svg", alt: "React icon", class: "tech-icon p-3" %>
          <% end %>
          <%= link_to "https://vuejs.org", target: "_blank", rel: "noopener" do  %>
            <%= image_tag "vuejs.svg", alt: "Vue.js icon", class: "tech-icon p-3" %>
          <% end %>
        </div>
      </div>
    </div>
    <hr class="my-5">
  </div>
</section>

app/views/pages/_terms_of_service_hero_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.7)), url(<%= asset_path('abstract-2.jpg') %>);">
  <div class="container">
    <h1 class="mt-5 mb-4 fs-1"><i class="fa-solid fa-file-lines"></i> Terms of Service</h1>
    <p class="text-lg text-gray-600">
      www.louisbourne.me
    </p>
    <p class="text-sm text-gray-500 mt-2">
      Last updated: December 10, 2025
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Portfolio home -->
<header>
  <%= render "landing_hero_banner" %>
</header>
<main>
  <%= render "featured_projects" %>
  <%= render "demo_day" %>
  <%= render "tech_stack" %>
  <%= render "related_skills" %>
  <%= render "education" %>
  <%= render "about_me" %>
  <%= render "contact" %>
</main>

app/views/pages/profile.html.erb
<!-- User profile -->
<header>
  <%= render "profile_hero_banner" %>
</header>
<div class="container">
  <section id="profile">
    <h2 class="mt-5 mb-4">Profile info</h2>
    <div class="row align-items-top">
      <!-- Avatar and info -->
      <div class="col-12 col-md-6 d-flex align-items-center">
        <%= image_tag "dog-pixar.jpg", alt: "Fun dog", class: "rounded-circle border border-dark avatar-profile me-3", style: "height: 20vh; width: auto;" %>
        <div>
          <p class="text-dark">Email: <span class="fst-italic purple"><%= @user.email %></span></p>
          <ul>
            <li class="purple"><span class="text-dark">Total projects created in app:</span> <%= @projects_total %></li>
            <li class="purple"><span class="text-dark">Personal projects created:</span> <%= @personal_projects_count %></li>
            <li class="purple"><span class="text-dark">Open source projects contributed to:</span> <%= @non_personal_projects_count %></li>
            <li class="purple"><span class="text-dark">Public Github repos:</span> <%= @public_repo_count %></li>
            <li class="purple"><span class="text-dark">Private Github repos:</span> <%= @private_repo_count %></li>
          </ul>
          <div class="d-flex justify-content-start">
            <%= link_to "Edit", edit_user_registration_path, class: "btn btn-outline-dark rounded-4" %>
          </div>
        </div>
      </div>
      <!-- Project list -->
      <div class="col-12 col-md-6">
        <div class="my-5">
          <h3>List of all <span class="purple"><%= @projects_total %></span> projects</h3>
          <p class="text-dark">
            <span class="text-success">Green</span> = Personal projects
            <span class="text-black">|</span>
            <span class="text-warning">Orange</span> = Open source projects
          </p>
          <ul>
            <% @projects.each do |project| %>
              <% if project.personal_project %>
                <% if project.private_repo %>
                  <li class="text-success"><%= project.title %> <span class="text-dark">-</span> <span class="text-danger">private</span></li>
                <% else %>
                  <li class="text-success"><%= project.title %> <span class="text-dark">-</span> <span class="text-primary">public</span></li>
                <% end %>
              <% else %>
                <% if project.private_repo %>
                  <li class="text-warning"><%= project.title %> <span class="text-dark">-</span> <span class="text-danger">private</span></li>
                <% else %>
                  <li class="text-warning"><%= project.title %> <span class="text-dark">-</span> <span class="text-primary">public</span></li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </section>
</div>